language: rust
sudo: false
env: RUST_BACKTRACE=1

before_script:
  - '[ -z "${REGISTRY_PASS:-}" ] || echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin'
  - docker pull marwes/try_gluon || true

script:
  - ./scripts/travis.sh

after_script:
  - docker images

deploy:
  provider: script
  script:
    - docker push marwes/try_gluon:dependencies
    - docker push marwes/try_gluon:builder
    - docker push marwes/try_gluon
  on:
    branch: master
