[package]
name = "try_gluon"
version = "0.5.0"
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"


[workspace]
members = ["gluon_master"]

[[bin]]
name = "try_gluon"
path = "src/app/main.rs"

[dependencies]
env_logger = "0.5"
failure = "0.1"
futures = "0.1.0"
glob = "0.2"
home = "0.3"
hubcaps = { git = "https://github.com/softprops/hubcaps", rev = "12ee80d" }
log = "0.4"
mount = "0.4.0"
persistent = "0.4.0"
regex = "0.2.7"
serde = "1"
serde_derive = "1"
serde_json = "1"
staticfile = "0.5.0"
structopt = "0.2"
tokio = "0.1"
hyper = "0.12"
hyper-tls = "0.3"

gluon = { version = "0.9", features = ["serialization", "web", "regex", "rand"], git = "https://github.com/gluon-lang/gluon", rev = "9a082df" }
gluon_format = { version = "0.9", git = "https://github.com/gluon-lang/gluon", rev = "9a082df" }
gluon_vm = { version = "0.9", git = "https://github.com/gluon-lang/gluon", rev = "9a082df" }
gluon_codegen = { version = "0.9", git = "https://github.com/gluon-lang/gluon", rev = "9a082df" }

gluon_master = { path = "gluon_master", features = ["serialization"] }

# [patch.crates-io]
# gluon_codegen = { path = "../gluon/codegen" }
# gluon_format = { path = "../gluon/format" }
# gluon_vm = { path = "../gluon/vm" }
# gluon = { path = "../gluon" }
